import { getDb } from "../api/queries/connection";
import {
  users,
  matches,
  bets,
  transactions,
  strategies,
  leaderboardEntries,
  virtualMatches,
  announcements,
  chatMessages,
} from "./schema";

const demoMatches = [
  {
    homeTeam: "Manchester City",
    awayTeam: "Real Madrid",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "Champions League",
    matchDate: new Date(Date.now() + 3600000),
    status: "live" as const,
    minute: 67,
    homeScore: 2,
    awayScore: 1,
    homeOdds: "1.85",
    drawOdds: "3.40",
    awayOdds: "4.20",
    overUnderLine: "2.5",
    overOdds: "1.95",
    underOdds: "1.85",
    bttsYesOdds: "1.75",
    bttsNoOdds: "2.05",
    homePossession: 58,
    homeShots: 14,
    awayShots: 8,
    homeShotsOnTarget: 6,
    awayShotsOnTarget: 3,
    homeCorners: 7,
    awayCorners: 3,
    isFeatured: true,
    isVirtual: false,
    flashEventActive: true,
    flashEventData: JSON.stringify({ question: "Goal in next 5 mins?", yesOdds: 2.5, noOdds: 1.5 }),
  },
  {
    homeTeam: "Arsenal",
    awayTeam: "Bayern Munich",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "Champions League",
    matchDate: new Date(Date.now() + 7200000),
    status: "scheduled" as const,
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    homeOdds: "2.10",
    drawOdds: "3.25",
    awayOdds: "3.50",
    overUnderLine: "2.5",
    overOdds: "1.90",
    underOdds: "1.90",
    bttsYesOdds: "1.65",
    bttsNoOdds: "2.20",
    isFeatured: true,
    isVirtual: false,
  },
  {
    homeTeam: "Barcelona",
    awayTeam: "Paris Saint-Germain",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "Champions League",
    matchDate: new Date(Date.now() + 18000000),
    status: "scheduled" as const,
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    homeOdds: "2.35",
    drawOdds: "3.40",
    awayOdds: "2.90",
    overUnderLine: "3.5",
    overOdds: "2.10",
    underOdds: "1.75",
    bttsYesOdds: "1.55",
    bttsNoOdds: "2.40",
    isFeatured: true,
    isVirtual: false,
  },
  {
    homeTeam: "Liverpool",
    awayTeam: "Inter Milan",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "Champions League",
    matchDate: new Date(Date.now() - 3600000),
    status: "finished" as const,
    minute: 90,
    homeScore: 3,
    awayScore: 0,
    homeOdds: "1.65",
    drawOdds: "3.80",
    awayOdds: "5.50",
    overUnderLine: "2.5",
    overOdds: "1.80",
    underOdds: "2.00",
    bttsYesOdds: "1.95",
    bttsNoOdds: "1.85",
    isFeatured: false,
    isVirtual: false,
  },
  {
    homeTeam: "Brazil",
    awayTeam: "Argentina",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "World Cup Qualifiers",
    matchDate: new Date(Date.now() + 86400000),
    status: "scheduled" as const,
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    homeOdds: "2.20",
    drawOdds: "3.10",
    awayOdds: "3.40",
    overUnderLine: "2.5",
    overOdds: "1.95",
    underOdds: "1.85",
    bttsYesOdds: "1.80",
    bttsNoOdds: "2.00",
    isFeatured: true,
    isVirtual: false,
  },
  {
    homeTeam: "France",
    awayTeam: "Germany",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "Friendly",
    matchDate: new Date(Date.now() + 43200000),
    status: "scheduled" as const,
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    homeOdds: "2.05",
    drawOdds: "3.30",
    awayOdds: "3.60",
    overUnderLine: "2.5",
    overOdds: "1.88",
    underOdds: "1.92",
    bttsYesOdds: "1.70",
    bttsNoOdds: "2.15",
    isFeatured: false,
    isVirtual: false,
  },
  {
    homeTeam: "Japan",
    awayTeam: "South Korea",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "AFC Asian Cup",
    matchDate: new Date(Date.now() - 7200000),
    status: "finished" as const,
    minute: 90,
    homeScore: 1,
    awayScore: 2,
    homeOdds: "1.90",
    drawOdds: "3.40",
    awayOdds: "4.00",
    overUnderLine: "2.5",
    overOdds: "2.00",
    underOdds: "1.80",
    bttsYesOdds: "1.85",
    bttsNoOdds: "1.95",
    isFeatured: false,
    isVirtual: false,
  },
  {
    homeTeam: "AI United",
    awayTeam: "Cyber Strikers",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "Virtual League",
    matchDate: new Date(Date.now() + 1800000),
    status: "live" as const,
    minute: 34,
    homeScore: 1,
    awayScore: 1,
    homeOdds: "2.50",
    drawOdds: "3.00",
    awayOdds: "3.10",
    overUnderLine: "2.5",
    overOdds: "1.90",
    underOdds: "1.90",
    bttsYesOdds: "1.60",
    bttsNoOdds: "2.30",
    isFeatured: false,
    isVirtual: true,
  },
  {
    homeTeam: "Neural FC",
    awayTeam: "Bot City",
    homeTeamLogo: "/images/team-placeholder.png",
    awayTeamLogo: "/images/team-placeholder.png",
    league: "Virtual League",
    matchDate: new Date(Date.now() + 5400000),
    status: "scheduled" as const,
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    homeOdds: "1.95",
    drawOdds: "3.40",
    awayOdds: "3.80",
    overUnderLine: "2.5",
    overOdds: "1.85",
    underOdds: "1.95",
    bttsYesOdds: "1.75",
    bttsNoOdds: "2.05",
    isFeatured: false,
    isVirtual: true,
  },
];

const demoAnnouncements = [
  {
    title: "Flash Event Live!",
    content: "Goal in next 5 minutes? Place your flash bets now on Man City vs Real Madrid!",
    type: "flash_event" as const,
    isActive: true,
  },
  {
    title: "Crypto Deposit Bonus",
    content: "Deposit with USDT and get 10% bonus on your first deposit!",
    type: "promotion" as const,
    isActive: true,
  },
];

const demoStrategies = [
  {
    userId: 1,
    title: "Home Favorite Strategy",
    description: "Bet on home teams with odds between 1.50-2.20 in major leagues",
    sportType: "football" as const,
    price: "0",
    winRate: "68.50",
    totalBets: 124,
    content: JSON.stringify({ rules: ["Home team odds 1.50-2.20", "Major leagues only", "Min 5 home wins in last 10"] }),
    isActive: true,
  },
  {
    userId: 1,
    title: "Over 2.5 System",
    description: "Systematic over 2.5 goals betting with statistical filters",
    sportType: "football" as const,
    price: "25",
    winRate: "62.30",
    totalBets: 89,
    content: JSON.stringify({ rules: ["Both teams avg > 1.4 goals", "Combined xG > 2.8", "No defensive teams"] }),
    isActive: true,
  },
  {
    userId: 1,
    title: "BTTS Gold Method",
    description: "Both Teams To Score - proven method with 65%+ success rate",
    sportType: "football" as const,
    price: "15",
    winRate: "65.20",
    totalBets: 156,
    content: JSON.stringify({ rules: ["Attack-minded teams", "Defensive weaknesses", "Historical H2H data"] }),
    isActive: true,
  },
];

async function seed() {
  const db = getDb();

  // Seed matches
  for (const match of demoMatches) {
    await db.insert(matches).values(match).onDuplicateKeyUpdate({
      set: { updatedAt: new Date() },
    });
  }
  console.log("✅ Matches seeded");

  // Seed announcements
  for (const ann of demoAnnouncements) {
    await db.insert(announcements).values(ann);
  }
  console.log("✅ Announcements seeded");

  // Seed strategies (will need actual user IDs later)
  // These will be seeded after first admin login

  console.log("🌱 Seeding complete!");
}

seed().catch(console.error);
